[package]
name = "libcommonplace_types"
version = "0.0.0"
authors = ["Wesley Aptekar-Cassels <me@wesleyac.com>"]
edition = "2018"

[dependencies]
blake3 = "0.3.7"
uuid = { version = "0.8.1", features = [ "v4", "serde" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
